### ISSUE TITLE
Arrows info doesnt raise

### ISSUE THREAD

**Issue by vos6434** [yurisuika/Raised#11]
Arrows HUD doesnt raise
https://www.curseforge.com/minecraft/mc-mods/arrows-info/
![2022-05-20_16 46 10](https://user-images.githubusercontent.com/21976486/169564723-734a589e-03f7-4064-8db9-f68469684570.png)

**Comment by yurisuika** [comment]
I just added support for this. You must be using the wrong version of one or both mods.
See #9

**Comment by vos6434** [comment]
My bad, I was one update below.
