### ISSUE TITLE
feat: raise chat to show above armor icons

### ISSUE THREAD

**Issue by luximus-hunter** [yurisuika/Raised#14]
This is similar to Gnemboms ChatUp. It would move the chat up by 10px or something, so it doesn't render on top of your armor icons. It think a mod like raised could totally include this as a new feature

**Comment by yurisuika** [comment]
I was actually planning to add a configurable offset for the chat! So it will still move with the rest of the HUD, but can be specifically tweaked just as you mention.

**Comment by luximus-hunter** [comment]
Awesome! Keep up the great work!
