### ISSUE TITLE
Chat is raised, but tooltip hitboxes are not

### ISSUE THREAD

**Issue by LordVertice** [yurisuika/Raised#15]
If you raise the HUD, it will move your hotbar and chat, but the hitboxes of chat tooltips will stay in place. Here's an example that you can see when trying to hover over a player name with advanced tooltips on: (you cannot see my mouse in this screenshot, but I placed it where my name would be if the HUD wasn't raised)

![Screenshot 2022-06-17 195431](https://user-images.githubusercontent.com/56739341/174352695-884940d0-e547-48ae-b9b0-08eefd979c55.png)

This happens regardless of my installed mods, so ignore the additional HUD elements.

**Comment by yurisuika** [comment]
Thanks I'll have this fixed in the next release!
