### ISSUE TITLE
Feature request: move boss health bar

### ISSUE THREAD

**Issue by SandWoodJones** [yurisuika/Raised#16]
Add an option for moving bosses' health bar so that it doesn't interfere with other mods (wthit/jade, etc)

**Comment by yurisuika** [comment]
If it is interfering with other mods, then that is probably up to the responsibility of those mods to not interfere with it. Raised does not affect the Boss bar at all, and changing the positioning of it when it doesn't need to be fixed would just cause a lot more mod conflicts. This is outside of the scope of Raised, which is to fix the broken hotbar.
