### ISSUE TITLE
[Request / 1.19.1] Update to new recommended forge build and 1.19.1.

### ISSUE THREAD

**Issue by murao-kun** [yurisuika/Raised#17]
There is recommended build of forge is out for 1.19. Also it might allow mod to work on 1.19.1.

**Comment by yurisuika** [comment]
Thanks, I was unaware of an update and see it is incompatible. I will update it for the latest 1.19.2 that seems to have come out now.

**Comment by yurisuika** [comment]
Seems it is all on Forge refactoring stuff. Should have an update out tonight.

**Comment by murao-kun** [comment]
Thank you!

**Comment by murao-kun** [comment]
Seems like that version is missing config. But at least works now!
