### ISSUE TITLE
[BUG] There is no config file on 1.19.2 forge version.

### ISSUE THREAD

**Issue by murao-kun** [yurisuika/Raised#18]
Just installed new update and seems like config file is not creating.

**Comment by yurisuika** [comment]
On the version it is built for, 43.0.7, it works on my end. What version of Forge are you using?

**Comment by murao-kun** [comment]
43.1.24

**Comment by yurisuika** [comment]
Looking at this again, now on 43.1.43, I still cannot replicate this. For now I am considering this closed. If you are still having this issue, please post logs or something, otherwise I can only assume it is something unrelated to Raised.

**Comment by murao-kun** [comment]
Yeah, with recent forge updates issue is fixed.
