### ISSUE TITLE
Doesn't work fully with Inventorio.

### ISSUE THREAD

**Issue by Xrey274** [yurisuika/Raised#2]
Inventorio is a mod that changes and enlarges the inventory. As well as that it also adds extra off hand slots. Raised, raises the normal hotbar as expected, but does not the offhand slots.
![image](https://user-images.githubusercontent.com/30723811/150692092-2dff27a4-d2ee-492a-bf4d-819001d06f73.png)

**Comment by yurisuika** [comment]
This looks like it runs into the same issue as #1.

**Comment by yurisuika** [comment]
As far as I am aware, the only way other mods can work with this properly is if they render their elements based on whether Raised is loaded.

The other option is that I fix the code in other mods via mixins. This would be on a mod by mod basis. This mod however is written in Kotlin, which is a language I don't know (and I am barely competent in Java), and I don't even know if you can make mixins for Kotlin code.

**Comment by yurisuika** [comment]
Well there we go, that wasn't so difficult. I am adding a patch for Inventorio in the next update.

![2022-01-23_17 34 49](https://user-images.githubusercontent.com/7410303/150708404-6767c999-6bca-4679-8690-a8006bc53633.png)
