### ISSUE TITLE
Need help getting it to work on Minecraft 1.17.1

### ISSUE THREAD

**Issue by HEROshineMC** [yurisuika/Raised#20]
Hi! Whenever I try to use this mod, I get this error:
![image](https://user-images.githubusercontent.com/60427702/186131465-6f40dbb8-9f73-49dd-b101-1beceff456e3.png)

This error says I need OpenJDK 17, but Minecraft 1.17.1 runs on OpenJDK 16. I tried running the game with JDK 17, and of course it crashes since it's the wrong version.

I'm using:
- Minecraft 1.17.1
- Fabric 0.14.9 for Minecraft 1.17.1
- Fabric API 0.46.1 for Minecraft 1.17.1
- Raised 1.1.2 for Minecraft 1.17.1

On the CurseForge page for this mod, this particular version is labelled as for Java 16, which makes sense, but it seems to need Java 17? I'm very confused 😅

Thanks in advance! :)

**Comment by HEROshineMC** [comment]
Oh! Silly me, I should have pasted the error here! I don't know if it's helpful at all but here it is:

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Raised' (raised) 1.1.2 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

I'm still confused why a mod for a Java 16 version of the game is requiring Java 17, something definitely seems wrong.

**Comment by yurisuika** [comment]
Ah yes sorry about this. I was expecting to have to have another release for it and deliver the fix then, but I suppose that never came and I forgot about this. I can replace the JARs on GitHub for now.

**Comment by yurisuika** [comment]
Will be properly fixed on the next Curseforge release which should be out soon!
