### ISSUE TITLE
[1.19] [Forge] [Bug]: Keys don't register

### ISSUE THREAD

**Issue by Fuzss** [yurisuika/Raised#21]
Hey there, the `RegisterKeyMappingsEvent` is a `IModBusEvent`, so it fires on the ModLifecycle event bus instead of the primary event bus. This line does nothing right now, you need to use the correct event bus:
https://github.com/yurisuika/Raised/blob/0954d47f5d6f88eb4880905f13f60808651c078f/src/main/java/com/yurisuika/raised/Raised.java#L119

**Comment by yurisuika** [comment]
Sorted out for the next update!
