### ISSUE TITLE
Reset Gui Position

### ISSUE THREAD

**Issue by CharlieThunkman** [yurisuika/Raised#22]
I downloaded this mod as part of a modpack and while spamming random hotkeys found the hotbar rising through my minecraft window. I thought I set it close to its original location but now I can't figure out where the hotbar is as it is off screen completely. All I ask is for a reset button that changes the position of the hotbar back to a viewable location.

**Comment by yurisuika** [comment]
This has already been added in the latest version 1.1.4!
