### ISSUE TITLE
Raised seems to be overextending the selector pixels into the buttons texture

### ISSUE THREAD

**Issue by kaveend** [yurisuika/Raised#23]
![image](https://user-images.githubusercontent.com/45495320/201428184-81bc8cd5-f3f4-47f9-b314-0e11449e28eb.png)

I found this issue while making a resource pack:
because of how I have made the Hotbar in my texture file, there are floating pixels from the button texture when it over-extends, this isn't really apparent with default textures. 
I would like to be able to set a value to something lower so this isn't an issue for me while retaining the floating Hotbar.

**Comment by yurisuika** [comment]
I cannot seem to replicate this, testing with a modified widgets.png to bring out any obvious issues. Raised came about because I noticed the selector was cut off in my own textures, so I am pretty sure all should be right as it is. You should not need to be adjusting its value to accommodate a resource pack.

What is your setup? Perchance this is a mod conflict?

If you would share your entire widgets.png I could test it myself.

**Comment by kaveend** [comment]
after testing, yes this does seem to be a mod conflict, albeit I'm not sure what is causing It,
here's the mod list and the widgets.png:
![widgets](https://user-images.githubusercontent.com/45495320/201557349-9ff7ad75-1888-482c-a619-5af7b2c2bb43.png)

- Advanced NBT Tooltips
- Animatica
- Anti-Ghost
- Appleskin
- Auditory
- Bedrockify
- Better Biome Blend
- Better Ping Display
- Better F3
- Blur
- Borderless Mining
- Better Sodium Video Settings
- Fabric Capes
- Charmonium
- Chat Heads
- CIT Resewn
- Clickthrough
- Continuity
- Cull Less Leaves
- DashLoader
- Drip Sounds
- Dynamic FPS
- Dynamic Sound FIlters
- Effective
- Enhanced Attack Indicator
- Enhanced Block Entities
- Entity Collision FPS Fix
- Entity Texture Features
- Entity Culling
- Extra Sounds
- Fabric Language Kotlin
- Fabric Skyboxes
- Fabrishot
- Farsight
- FerriteCore
- Flour's Various Tweaks
- Forget Me Chunk
- Gamma Utils
- Illuminations
- Indium
- Inspecio
- Interactic
- Inventory Control Tweaks
- Iris
- Item Model Fix
- Krypton
- Lambdas Dynamic Lights
- Language Reload
- LazyDFU
- Lithium
- Make Bubbles Pop
- Memory Leak Fix
- Minimal Menu
- Mixin Conflict Helper
- Mod Menu
- Mouse Wheelie
- No Resource Pack Warnings
- No Screen Bobbing
- Not Enough Crashes
- Not Enough Animations
- OptiGUI
- Pling
- Presence Footsteps
- Puzzle
- Replay Mod
- Skip Transitions
- Smooth Swapping
- Sodium
- Sound Physics Remastered
- Spark
- Starlight
- Status Effect Timer
- Suggestion Tweaker
- Thorium
- TieFix
- Title Fixer
- ToolTip Fix
- Audio Engine Tweaks
- Very Many Players
- Wavey Capes
- Your Options Shall Be Respected
- Zoomify

**Comment by yurisuika** [comment]
Ah, I see you are using Bedrockify. Depending on whether you just want Raised's hotbar height adjustability or the rest of the Bedrock-styled HUD (and Bedrock features) you just gotta choose one or the other. Unless you can toggle the HUD changes with Bedrockify, that is, but AFAIK there is no point in using both together.
