### ISSUE TITLE
Inventory Profiles Next incompatibility

### ISSUE THREAD

**Issue by thimblebird** [yurisuika/Raised#24]
See https://github.com/blackd/Inventory-Profiles/issues/256#issuecomment-1364063765

**Comment by blackd** [comment]
Here is an example how other mods do it 
https://github.com/Crendgrim/AutoHUD/blob/0c10c063cf97c1631d0ff51d17df74596189adce/src/main/java/mod/crend/autohud/compat/mixin/inventoryprofilesnext/LockSlotsHandlerMixin.java

**Comment by yurisuika** [comment]
Thanks for the report! This will be out in the next update.

Cool GUI editor btw!
