### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by RyanCR03** [yurisuika/Raised#3]
https://pastebin.com/b8vL1LC3

**Comment by yurisuika** [comment]
It looks like your mod Better Mount HUD is giving the crash. Both of our mods modify the same constant and thus are incompatible.

**Comment by yurisuika** [comment]
It seems that BMH has found a way to make it compatible, and from what I see they have done I can do mine the same way and drastically improve compatibility with other mods! While BMH has taken itself to become compatible with Raised, I will nevertheless return the favor to any other mod and do the same. Version 1.0.2 will contain these improvements!
