### ISSUE TITLE
Hotbar lowered

### ISSUE THREAD

**Issue by zlynn58** [yurisuika/Raised#31]
In my Valhelsia 5 server, my hotbar seems to randomly go down like this until I delete and reinstall the entire Valhelsia 5 profile. Is there a way to fix this quickly or does it require a full restart each time? I've attached a picture of it, aswell. 
![2023-02-13_21 10 36](https://user-images.githubusercontent.com/105879157/218629638-fa49edd5-7c66-485c-86b3-9ae2b93ebb0f.png)

**Comment by yurisuika** [comment]
I can't say I know it, but perhaps are you pressing some key when it happens? Raised has keybinds (in addition to the new commands) to adjust the hotbar height.

**Comment by zlynn58** [comment]
The keybinds for it were really messed up. The +/- keys that were used for moving it up and down were also being used by a ton of other mods... so it's all good now! Thanks for the help!
