### ISSUE TITLE
[Universal] Atlas Combat breaks Raised 's features.

### ISSUE THREAD

**Issue by Cixon** [yurisuika/Raised#39]
I'm able to get the hearts, armor, and hunger to move with raised but hotbar stays.... can you please add compat with Nostalgic tweaks?

mod: https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks

**Comment by yurisuika** [comment]
Sure, I'll check it ou!

**Comment by Cixon** [comment]
sweet, thanks!

**Comment by yurisuika** [comment]
![image](https://github.com/yurisuika/Raised/assets/7410303/53a62401-36ab-49f4-9a35-023441b0dc46)
I cannot seem to replicate this. What is your setup?

**Comment by Cixon** [comment]
i use 1.18.2 forge. let me send config

**Comment by yurisuika** [comment]
Interesting, I have tried that version specifically and it worked? You are saying it is specifically just the hotbar that does not change?

**Comment by Cixon** [comment]
[nostalgic_tweaks.txt](https://github.com/yurisuika/Raised/files/11713132/nostalgic_tweaks.txt)

^place in config directory.

[nostalgic_tweaks.txt](https://github.com/yurisuika/Raised/files/11713133/nostalgic_tweaks.txt)
^place in config \ nostalgic_tweaks

**Comment by Cixon** [comment]
they are .txt files since git-hub will not allow me to send .json. you'll need to rename.

**Comment by yurisuika** [comment]
![image](https://github.com/yurisuika/Raised/assets/7410303/fc19fc77-319c-4719-8102-7caf90650ab2)
1.18.2 Forge without your configs...
![image](https://github.com/yurisuika/Raised/assets/7410303/1897945c-8628-4523-821d-be457f4eb9d0)
And with your configs...

I am not yet able to replicate.

This is using latest versions of NT and Architectury (2.0.0-Beta-8.3 & 4.11.93). Is that what you have as well?

**Comment by Cixon** [comment]
I am... there must be a different mod interrupting this.

**Comment by Cixon** [comment]
I'm going to disable a few mods and rename this title once I find the issue, sorry for misleading you. I do appreciate your patience with me!

**Comment by Cixon** [comment]
Found the issue. It's from a mod called Atlas Combat. I use v1.1.5 because they broke client start_up phase in v1.1.6.

https://legacy.curseforge.com/minecraft/mc-mods/atlas-combat/files/4552632

**Comment by yurisuika** [comment]
Unfortunately this mod basically copies the hotbar method basically except for the last section concerning the attack indicator, and adds a bunch of stuff from what I guess is the combat test concerning shields and whatnot at the end. It then injects all of that at the very start of the hotbar method, so then it basically overwrites the vanilla hotbar stuff without using an actual overwrite.

You cannot mixin to other mixins, so I can not do anything about this. There are ways they could do this mixin without breaking this compatibility by just making the vanilla attack indicator section not run, and then adding the combat test stuff before `RenderSystem.disableBlend()`;, but that would have to come on their end.

**Comment by yurisuika** [comment]
At least then the hotbar would raise, the attack indicator replacement would not be raised if done in the same way it is there AS IS.

**Comment by Cixon** [comment]
I will reference this to the Atlas team in hopes of a fix. Thank you for being very informative!

**Comment by yurisuika** [comment]
I might be wrong, it could work... I'll try to build it myself and test it out.

![image](https://github.com/yurisuika/Raised/assets/7410303/ab880a84-18e4-43c2-b779-bd828f9854f9)
Raised basically just changes a value in `drawTexture` for the hotbar to change everywhere in that method. Mixin priority is set to `-1` to make it run last. I'd think this would mean it would change it for the mixins for Atlas, but apparently it does not want to do so. This was done way back to make it compatible with another mod that changed stuff via mixins.

**Comment by yurisuika** [comment]
![image](https://github.com/yurisuika/Raised/assets/7410303/76a4b66f-a81a-4a51-b6bc-06acdd64cd7f)
 Ignore the health icons etc because this is Fabric, on Forge they work out of the box because of Forge hooks, but on Fabric it probably overwrites it again so much the same would be done... Anyways I replaced the mixin method in that mod with THIS:

![image](https://github.com/yurisuika/Raised/assets/7410303/cb29e6fb-cbd4-4ec4-94c6-0127b03a80b0)

It can probably be done cleaner, but this is the quick and dirty to show it can work.

**Comment by yurisuika** [comment]
Actually hold up, I forgot to cancel the original attack indicator and notice that there is a second one showing up at the bottom, so this might not work. Status bars are not moving either when done the same way (and changing the ModifyVariable to a ModifyArg in Raised much the same...

**Comment by yurisuika** [comment]
![image](https://github.com/yurisuika/Raised/assets/7410303/31123005-6e82-44c5-ac3f-d1ed36d45d12)
![image](https://github.com/yurisuika/Raised/assets/7410303/820d556f-7a00-428c-9874-bd4300809cfe)
Okay yeah, making the original not work you have this, that other one this mod adds in shows up very briefly but it is there. Seems to come a little later too. I have not tried the combat test so I don't know what is different.

Back to the drawing board as far as getting this to work. I might however change the modifyvariables to modifyargs in Raised though regardless. I know modifyvariable is always better to use than modifyconstant, but it might be inferior to modifyarg.

**Comment by Cixon** [comment]
Oh wow didn’t expect all this! 👏🏼👏🏼👏🏼

ig you could make it a separate project to keep Raised’s original code. I really appreciate you for going the extra mile one this, seriously.

**Comment by Cixon** [comment]
> Oh wow didn’t expect all this! 👏🏼👏🏼👏🏼
> 
> ig you could make it a separate project to keep Raised’s original code. I really appreciate you for going the extra mile one this, seriously.

or a config setting to override the initial settings/mixins…

**Comment by yurisuika** [comment]
No, this is the code for that other mod. It won't work sadly.
