### ISSUE TITLE
Incompatibility: Detail Armor Bar mod is not raised

### ISSUE THREAD

**Issue by Khodyn** [yurisuika/Raised#4]
[Detail Armor Bar](https://github.com/RedLime/DetailArmorBar)

without Raised:
![image](https://user-images.githubusercontent.com/49518050/156197645-bdd30d6f-def5-4476-8e8f-64ed0acb8fe1.png)
with Raised:
![image](https://user-images.githubusercontent.com/49518050/156197959-d0ebfe7a-423b-4a60-9a05-8867aeb48098.png)

![image](https://user-images.githubusercontent.com/49518050/156197815-066e8a9c-1263-4028-a2ae-7b77c6cdb4e7.png)

**Comment by yurisuika** [comment]
I'll look into adding support for it!

**Comment by yurisuika** [comment]
Added to 1.0.3
