### ISSUE TITLE
Create Toolbox Compatibility

### ISSUE THREAD

**Issue by GamingMicrowave** [yurisuika/Raised#40]
Create's toolbox overlay doesn't get raised 

![](https://github.com/yurisuika/Raised/assets/132798365/94940496-7bec-4869-b985-e4d5b3bd0364)

The issue doesn't happen with Fabric

### Versions:
Minecraft: 1.19.2
Forge: 43.2.14

Raised 1.2.2
Create 5.1b

**Comment by yurisuika** [comment]
Yes, v0.5.1 of Create had some changes, you can the fixed builds for Raised currently off of GitHub.

Fabric Create is a port made by somebody else, so it still works. All it is is restructuring of packages, so it is possible the port may not change that? We'll see what comes. :D

**Comment by yurisuika** [comment]
Actually, it seems the Backtank had some additional changes to its code for 0.5.1, so that will be addressed as well.

**Comment by yurisuika** [comment]
https://github.com/yurisuika/Raised/actions/runs/5309457751

You should find everything works now with this build!
