### ISSUE TITLE
Mod is incompatible on 1.20.1 with Create. Raised mixin needs to be updated

### ISSUE THREAD

**Issue by celsiusqc** [yurisuika/Raised#42]
![image](https://github.com/yurisuika/Raised/assets/63996164/f7c23e27-11c6-4ef2-93c2-ab35425c5c92)
https://gist.github.com/celsiusqc/284e3db66288d885e7f89a5f0132942a

**Comment by yurisuika** [comment]
This is already done for a couple weeks! The release has not been uploaded to popular repos yet, but you can get it on the Actions page or the release.

EDIT: I see that 1.20 has been created for it, I can add in the mixin again for that, it is actually removed since.
