### ISSUE TITLE
Crashing with Farmer's Delight

### ISSUE THREAD

**Issue by pajicadvance** [yurisuika/Raised#43]
`[11:27:54] [Render thread/ERROR]: Mixin apply for mod raised failed #raised:raised.mixins.json:mods.FarmersDelightMixin$NourishmentHungerOverlayMixin from mod raised -> com.nhoryzon.mc.farmersdelight.client.gui.NourishmentHungerOverlay: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Redirect annotation on redirectRender could not find any targets matching 'Lcom/nhoryzon/mc/farmersdelight/client/gui/NourishmentHungerOverlay;renderNourishmentOverlay(Lnet/minecraft/class_4587;)V' in com.nhoryzon.mc.farmersdelight.client.gui.NourishmentHungerOverlay. Using refmap raised.refmap.json [PREINJECT Applicator Phase -> #raised:raised.mixins.json:mods.FarmersDelightMixin$NourishmentHungerOverlayMixin from mod raised -> Prepare Injections ->  -> redirect$ejk002$raised$redirectRender(Lnet/minecraft/class_1041;)I -> Parse]`

[Full log](https://mclo.gs/d4g1nKp)

Farmer's Delight got an update today so I assume Raised's mixin needs to be updated.

**Comment by yurisuika** [comment]
I think its just a signature change of the method, but what is ironic is that I had removed mod support for mods that weren't around in 1.20 yet cause I figured maybe stuff might change, but then just before the last release I tossed it back in.

But in this I found that Farmer's Delight had already added compatibility for Raised, but it was with the old object names that I replaced. So I guess I just need to remove Farmer's Delight support and add in legacy compatibility for that object name and that will fix it.

I have been thinking about breaking out mod support into additional files cause it will make updating mod support easier and having less releases overall, so this fix may wait on a release until that is done.
