### ISSUE TITLE
AppleSkin Incompatibility

### ISSUE THREAD

**Issue by ArcticFox037** [yurisuika/Raised#44]
Seems to incompatible with the newest version of AppleSkin; the overlays provided by that mod just stay instead of moving with the hotbar.

I've only tested AppleSkin 2.5.0 on 1.20.1 but I will test more versions later.

**Comment by yurisuika** [comment]
Is this for version 2.0.0? You've not downloaded the add-on file. All mod support is now done via add-ons for modularity.

**Comment by ArcticFox037** [comment]
Ah, I've only just realised that's what you meant by 'files'. I never opened the collapse in releases and none of the files show up in Modrinth. Apologies.

**Comment by yurisuika** [comment]
Yes, it is a change that will surely catch a few people off guard for a while, but I promise it will be a much better long-term solution.

Unfortunately Modrinth locks down HTML styling so I can't make a big red disclaimer header like on CF. Maybe I gotta make it an image? haha
