### ISSUE TITLE
AppleSkin HUD misaligned

### ISSUE THREAD

**Issue by NGGiovannii** [yurisuika/Raised#47]
I have just installed the mod and I can already say that i really enjoy it!
But one of the mods that I use in my vannilla+ modpack is AppleSkin. And the HUD for saturation and hunger does not align with the hotbar since it wont be coming up with it.
Here is a screenshot comparasion:
https://i.imgur.com/vAKtyQh.png

**Comment by yurisuika** [comment]
You need to download the appropriate add-on file for Appleskin if using Raised 2.0.0. You will find these as additional files on any respective repo.
