### ISSUE TITLE
Armor Chroma for Fabric compatibility

### ISSUE THREAD

**Issue by vos6434** [yurisuika/Raised#48]
Armor Chroma for Fabric does not get raised resulting in hearts touching the armor bar.
![incompatability](https://github.com/yurisuika/Raised/assets/21976486/fc82d23c-9ed8-415d-b532-7468288bf3cb)

**Comment by yurisuika** [comment]
I'll see to this shortly!

**Comment by yurisuika** [comment]
![2023-08-22_15 53 42](https://github.com/yurisuika/Raised/assets/7410303/7cf86b3d-b5bb-446e-9ca3-b8d70dd77279)
Sorry for the delay, I was trying to finish up some other work first and then ran into some medical problems, but I am now seeing to get this finished ASAP.

As you can see from the image, the Fabric 1.20.1 version is done. I will backport it and then see if the Forge version needs a fix as well.

**Comment by yurisuika** [comment]
Fabric is done and pushed! You can find working versions in the latest Actions tab.

I'll see if Forge needs support, and if so do the same.

**Comment by yurisuika** [comment]
Ah well I see the Forge version hasn't had an update since 1.12, well nevermind!
