### ISSUE TITLE
feature request: adjustable height

### ISSUE THREAD

**Issue by akirapink** [yurisuika/Raised#49]
points for including this: recreating the look of old console versions of minecraft! many people have nostalgia for those
points against including this: this might be better suited in a different, bigger mod that changes other ui components

![image](https://github.com/yurisuika/Raised/assets/33667869/8093a3c7-f484-4583-af11-e49f73667537)

**Comment by yurisuika** [comment]
Raised already features adjustable height. You can control it with the keybinds or the commands or by editing the config directly.
