### ISSUE TITLE
Raised not updating offset unless I scroll through the hotbar

### ISSUE THREAD

**Issue by twizinho** [yurisuika/Raised#50]
[Fabric 1.20.1]
For some reason, my current Raised mod [version: Fabric-1.20.1-2.0.0] doesn't seem to update the offset when I press the assigned buttons to move the hotbar up and down, it ONLY updates the offset when I scroll through any position on my hotbar.

wish I could show a video of the situation but my PC isn't exactly the best, so sadly I can't send any videos, only images, but either way, I think these images show what is happening.

![image](https://github.com/yurisuika/Raised/assets/95052258/5fd807c2-c252-4a3a-9c0a-affed32cea1c)

because of the error I'm having, it seems to also be conflicting with Appleskin maybe? i don't exactly know for sure but.... either way, this is weird.

**Comment by yurisuika** [comment]
In 2.0.0 Appleskin support is a separate file to download, but lacking that would not cause this.

From what I can see, it looks like your experience bar is not moving, but also the hearts/food is way above where it should be? Normally 7 above the selector, but here it is 15. That isn't quite enough extra room for another row of stats icons, so I don't know what exactly is going on, but it is probably some other mod conflicting.

If you can narrow down what mod it might be, I can see about support for it.

The scroll behaviour is indeed strange, as you shouldn't be able to bind the scroll wheel as a key. Perhaps this is some external software? Or it could be the aforementioned mod conflict.

If you could also provide a log, that would be a start.

**Comment by twizinho** [comment]
> In 2.0.0 Appleskin support is a separate file to download, but lacking that would not cause this.
> 
> From what I can see, it looks like your experience bar is not moving, but also the hearts/food is way above where it should be? Normally 7 above the selector, but here it is 15. That isn't quite enough extra room for another row of stats icons, so I don't know what exactly is going on, but it is probably some other mod conflicting.
> 
> If you can narrow down what mod it might be, I can see about support for it.
> 
> The scroll behaviour is indeed strange, as you shouldn't be able to bind the scroll wheel as a key. Perhaps this is some external software? Or it could be the aforementioned mod conflict.
> 
> If you could also provide a log, that would be a start.

it probably could be my launcher, this is not the only issue i've been having, so maybe it's my launcher, just maybe
for now, i'll change my main launcher to LabyMod, see if something happens, just for testing.

**Comment by twizinho** [comment]
good news, it WAS my launcher LMAO

the launcher was in beta so, maybe that was the problem
the only problem i'm having problem right now is the Appleskin's icons not having the right placements, maybe i can find something to mess with them

**Comment by yurisuika** [comment]
As I said, you need to go to the additional files on the release for v2.0.0 and get the Appleskin support.

This change will probably be reverted in the next update, however, as CF/Modrinth do not very well support their additional files in any form of promotion on site.

**Comment by twizinho** [comment]
> As I said, you need to go to the additional files on the release for v2.0.0 and get the Appleskin support.
> 
> This change will probably be reverted in the next update, however, as CF/Modrinth do not very well support their additional files in any form of promotion on site.

just got the files you said, and now it's working perfectly
thanks for the advice yuri :D
rlly proud of you for creating this mod btw, it's so simple yet so good, nice job on that, honestly :3
