### ISSUE TITLE
Simple armor hud Compatibility

### ISSUE THREAD

**Issue by MrMyror** [yurisuika/Raised#51]
It's a small mod, but it would be nice for a compatibility addon as it currently cuts into the hunger bar with the hotbar raised two up. [Here](https://modrinth.com/mod/simple-armor-hud) is the link.

**Comment by yurisuika** [comment]
Sorry for the delay, but I will see to it now!

**Comment by yurisuika** [comment]
Unfortunately, this mod does its calculations directly in mixins, which makes it impossible to modify from my end.

However, if you open up a ticket with them, they can add compatibility for Raised on their end.
https://github.com/yurisuika/Raised/wiki/Compatibility#adding-compatibility
