### ISSUE TITLE
Detail armor bars protection effects doesn't work?

### ISSUE THREAD

**Issue by DeadbushCarrot** [yurisuika/Raised#52]
I have the Add-on file installed 
quick thing I want to say you should say where the add-on files are located at cause I looked for few weeks now until recently

**Comment by yurisuika** [comment]
Can you be more specific and perhaps show some screenshots?

As far as support goes, it currently supports moving the armor icons. If there is some newer addition to the mod that I am not aware of that needs support, please detail what it is so I may look for it.

**Comment by DeadbushCarrot** [comment]
It was exordium just warn people to turn off buffer health to fix it but I don't know why it breaks the animation only when the Add-on is used!?
