### ISSUE TITLE
[BUG] (Fabric) AppleSkin Compatability

### ISSUE THREAD

**Issue by DanCodes-YT** [yurisuika/Raised#53]
Apple skin saturation points aren't level with the hunger anymore.
![image](https://github.com/yurisuika/Raised/assets/109990416/4a90d10e-6c7b-4741-955a-dc4a24f5c4cc)

**Comment by yurisuika** [comment]
You need to install the Appleskin support file with version 2.0.0, listed under each version's release as an additional file.
