### ISSUE TITLE
Compatibility for Health Overlay

### ISSUE THREAD

**Issue by foxinacove** [yurisuika/Raised#6]
I'm not too sure which mod needs to adapt to the other, but since I saw another issue with Detailed Armor, I figured I'll make an issue here!

The [Health Overlay](https://github.com/Terrails/HealthOverlay) mod makes health above 20 display over the original 10 hearts, but it doesn't raise with Raised.
With Raised:
![image](https://user-images.githubusercontent.com/102625726/163712282-c4bbfc67-cfd1-452f-8a56-cfa9d44b445c.png)
Without Raised:
![image](https://user-images.githubusercontent.com/102625726/163712556-b1de4b18-0301-4ba7-a0b7-52d46403173c.png)

**Comment by yurisuika** [comment]
It must be replacing the entire hearts bar I suppose, seems unnecessary for an overlay, but what do I know. I'll provide compatibility for it.

**Comment by yurisuika** [comment]
Added in 1.0.7
