### ISSUE TITLE
[Bug] [Fabric/Quilt 1.20.1] Mod pages/configs/guis are also raised in 3.0.0 

### ISSUE THREAD

**Issue by Aninuscsalas** [yurisuika/Raised#66]
When the hotbar is raised, modded guis, like settings screens, config pages, other full window guis are also raised.

Some mods that have this issue:
- Iris
- Better Stats Screen
- Some FancyMenu screens

Example:
![Screenshot from 2023-10-14 17-05-32](https://github.com/yurisuika/Raised/assets/68734661/d04bfea1-f087-48c8-86df-b9c92cd1a375)
![Screenshot from 2023-10-14 17-05-39](https://github.com/yurisuika/Raised/assets/68734661/8d002878-c57a-463b-b37e-8e02cf8ca35d)
![Screenshot from 2023-10-14 17-07-27](https://github.com/yurisuika/Raised/assets/68734661/f8dd34d9-977a-4ba8-a903-ae633349ddaf)

Logs:

[https://mclo.gs/AfvkMUs](https://mclo.gs/AfvkMUs)

**Comment by antieksi** [comment]
Just noticed that you also wrote about this, I do have the same issue, though on Fabric.
Do you have the GUI moved up in resourcepack settings?

**Comment by Aninuscsalas** [comment]
> Just noticed that you also wrote about this, I do have the same issue, though on Fabric. Do you have the GUI moved up in resourcepack settings?

Sometimes, if i only have raised installed then it doesnt happen, but when using it in my modpack it happens

Also, the Hud and Chat heights break different things...

**Comment by yurisuika** [comment]
Setting the config option for extended mod support to false seems to resolve this.

The implies that Iris's shaders menu is rendered at either the head or tail of the render method for the HUD.

You may find some mods that require that support to be enabled to move their HUD elements, however.

**Comment by yurisuika** [comment]
I can confirm the same course of action must be taken with Better Statistics Screen.

**Comment by yurisuika** [comment]
I haven't figured out how to get FancyMenu to work, but I'll take your word for it. It mostly likely requires the same course of action.

Anyways, this was foreseen and is the reason why this is a config option. I will update the wiki to include these on a list of mods which require extended mod support set to false.
