### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by antieksi** [yurisuika/Raised#67]
3.0.0 for Fabric 1.20.1, there is no such bug in 2.0.0.
How much GUI is moved up depends on how much the hotbar is. I suspect Blur to also be the reason for this.
Only appears while in game (both single- and multiplayer).

![изображение](https://github.com/yurisuika/Raised/assets/95758843/563082d6-5878-4cd8-9a25-1b1090e8cf0d)

**Comment by antieksi** [comment]
Blur isn't the reason at all.

Here's my mod list: https://pastebin.com/cM0PqGjt

**Comment by yurisuika** [comment]
From another bug report (as you have written in), Iris and Better Statistics Screen on Fabric (which you have) require extended mod support set to false.

Mod menu seems to work fine on my end, with those installed as well.

Try disabling that option and report back. If that resolves it, perhaps we can figure out which mod it is and add it to the wiki.

**Comment by antieksi** [comment]
Not sure where that setting is located

**Comment by antieksi** [comment]
Guess I had to join singleplayer/multiplayer to update the config. I've turned it off, now everything seems working as intended

**Comment by yurisuika** [comment]
If you figure out what mod it was, let me know so I can add it to the wiki.
