### ISSUE TITLE
Pickup Notification compatibility

### ISSUE THREAD

**Issue by Latino2k7** [yurisuika/Raised#68]
Can u Add Compatibility Plz 

Fabric
MC Version 1.20.2
Mod https://modrinth.com/mod/pickup-notifications

![2023-10-23_00 44 00](https://github.com/yurisuika/Raised/assets/37272834/f81b6840-a7d3-4124-b4c9-2a8cf33cd5e6)

**Comment by yurisuika** [comment]
It looks like it is raising it? I don't see the issue. If you wish it to not raise, try disabling extended mod support.

**Comment by yurisuika** [comment]
Yes, I can confirm that disabling extended support will cause it to not move. But, if you have another mod which requires extended support, this mod has a configurable ability to change the Y offset.

**Comment by Latino2k7** [comment]
i disable extended support and work fine now thx
