### ISSUE TITLE
Allow users to change how high the Hotbar will go

### ISSUE THREAD

**Issue by zndrmn** [yurisuika/Raised#7]
Add a config that lets users change how many pixels the hotbar will be raised to.

**Comment by yurisuika** [comment]
I have considered it. I definitely would not use any sort of dependency asides from FAPI though, as I consider it essential that I can release this for any snapshot that comes out.

**Comment by wafflecoffee** [comment]
This is entirely mixins -- does it even need to have FAPI?
Here's a one-class config library which is easily maintainable across versiosn: [MidnightConfig](https://github.com/TeamMidnightDust/MidnightLib/blob/main/src/main/java/eu/midnightdust/lib/config/MidnightConfig.java) ([usage/docs](https://github.com/TeamMidnightDust/MidnightLib/wiki/Using-MidnightConfig))

**Comment by yurisuika** [comment]
I have used that (and TinyConfig, what it was created from). I have actually already created a version using that in testing, but I would like something simpler if possible, as it is quite a lot added to just change an int value. 

I guess what I was trying to say is I would not use Cloth Config.

**Comment by yurisuika** [comment]
I'll ask around for some alternatives to look at, otherwise I would probably use TinyConfig (and maybe try to strip it out a bit). It really can be hella barebones for what it is for.

Was also testing a hotkey based solution that only held in memory, but yeah that would probably be pretty annoying. Was very simple though.

Either way you still need FAPI to register the config and for any keybinds.

**Comment by yurisuika** [comment]
One issue with these is that they are only made for Fabric and I'd have to port them to Forge if I wanted to use them.

**Comment by yurisuika** [comment]
![2022-05-05_03 44 41](https://user-images.githubusercontent.com/7410303/166908266-ffa549ac-a880-4425-a6fe-1811d0e33917.png)
Well for now I will release a version with the simple adjustability. I have realized that the Inventorio support was never fully updated to use the additional pixel change, and I didn't put the new plugin in the right folder for 1.19, so it could use a new release anyways.

**Comment by yurisuika** [comment]
1.1.0 will feature this adjustability along with some other improvements.
