### ISSUE TITLE
Versioning error on modrinth

### ISSUE THREAD

**Issue by Arthurmeade12** [yurisuika/Raised#70]
Concerning this modrinth version: https://modrinth.com/mod/raised/version/Fabric-1.19.2-3.1.0
The versions on modrinth are labeled as 1.18.2 - 1.19.2, however the fabric.mod.json only allows compat with 1.19 - 1.19.2.
Therefore, the jar fails to launch on 1.18.2 despite being marked as being able to do this.
Please either change the fabric mod json or the modrinth versions to make this clearer to users.

**Comment by yurisuika** [comment]
Hi, please refrain from making issues regarding Modrinth here. This is for the code, not the repository.
