### ISSUE TITLE
Raised offsets texts in HUD overlays

### ISSUE THREAD

**Issue by dicedpixels** [yurisuika/Raised#71]
When running with mods that adds text overlays such as Sodium Extra's FPS overlay or MiniHud's Info Lines, text appears offset vertically to the top.

![2023-11-09_18 18 39](https://github.com/yurisuika/Raised/assets/121529979/d2920b1b-b11c-48f0-a40a-2dbf58ac3965)

#### Sodium Extra settings:

Text Contrast is set to Background.

![2023-11-09_18 31 01](https://github.com/yurisuika/Raised/assets/121529979/83889dc5-8878-48d9-a907-18d9f284dd38)

All other settings, including Raised's are default.

Logs: [prism-latest.txt](https://github.com/yurisuika/Raised/files/13308383/prism-latest.txt)

---

Edit: I was playing around with the settings and turning off "Support" seems to fix this. While this fixes my specific issue, I'll wait for any feedback from the author.

**Comment by yurisuika** [comment]
That is the purpose of the Extended Mod Support, it allows for translating mods that associate their HUD elements vaguely with vanilla ones, not based on any HUD element that Raised aims to translate. If mods are associating their HUD elements "properly", then it shouldn't be needed.

On Forge the vagueness is less forgivable than on Fabric, but at the end of the day the contingency for mods expecting their stuff to be altered like Raised does probably isn't in the playbook.
