### ISSUE TITLE
Incompatibility with BerdinskiyBear Armor HUD

### ISSUE THREAD

**Issue by vos6434** [yurisuika/Raised#8]
Armor hides but the HUD does not, It also is not moved up.
https://user-images.githubusercontent.com/21976486/164943265-02a5c846-84fb-4c41-a28c-51b05524133a.mp4

**Comment by vos6434** [comment]
I've just realised the mod has a config to offset the HUD.

**Comment by yurisuika** [comment]
Someone already mentioned this one off-site. I should probably add a list concerning what works and what doesn't.
