### ISSUE TITLE
[Compatability] Arrows Info

### ISSUE THREAD

**Issue by BeastSlayer666** [yurisuika/Raised#85]
The arrows info slot doesn't align when using Raised and Arrows Info.

![image](https://github.com/yurisuika/Raised/assets/87861236/4f3675ac-edeb-4e85-baa4-fc7c5022c15a)

**Comment by BeastSlayer666** [comment]
Disabling share in the raised config fixes this issue

**Comment by yurisuika** [comment]
Yep that is what that option was specifically added for, Arrows Info was the initial reason Raised got Object Share support in the first place, but a change to how Raised works means it isn't needed anymore for several mods that had were using it. Thus the share option was added to zero out the shared value.
