### ISSUE TITLE
Movable Status Effect HUD and chat?

### ISSUE THREAD

**Issue by heythisisreal** [yurisuika/Raised#86]
This is more of a suggestion than an issue. I was wondering if at some point, could you add a way to move the status effect HUD slightly down and to the left, and the chat slightly to the right? I've been looking for a fabric mod that does exactly and only that, though unfortunately I have not found any yet.

I don't think I've seen many other HUD mods as simple yet influential as yours so I found it very fitting for me to ask you specifically, though I perfectly understand that these suggestions aren't very much related to the hotbar bug that started the idea of this mod in the first place. At the end of the day, it's all obviously up to you, and ngl I'll still use Raised regardless of what you add or not, it's so good lol...

Lastly, I sincerely want to say that thank you for putting your time and effort to create such an awesome mod! Because of it, I was able to make my texture pack work flawlessly after hours of headaches re-editing the hotbar.

Have an awesome day!

*Concepts:*

![Screenshot 2024-03-25 102252](https://github.com/yurisuika/Raised/assets/115737975/25a70a5e-a19a-4184-9b40-144eb1843f85)
![Screenshot 2024-03-25 102340](https://github.com/yurisuika/Raised/assets/115737975/c26af68f-3628-444e-a9f4-86e6010866af)
![Screenshot 2024-03-25 102836](https://github.com/yurisuika/Raised/assets/115737975/e862f2cd-eef3-41dd-8e1d-0cc1e43a9dab)

**Comment by yurisuika** [comment]
This is something I have actually done before but have never been satisfied with the solution I have come up with to make a release out of it.

I like trying to keep things pretty simple, so perhaps a single option/button to toggle full screen movement would be best suited to that. I have tried more complicated solutions like having sets for every element type for what direction they should move, but that does make things look a bit messy and is sort of antithetical to the idea.

So, if such a mode is enabled, we would see hotbar section move up, chat up and right, status down and left, bossbar down, and scoreboard left.

The only issue with this idea is capturing mods which do not associate with any element. Some may be placed in spots that mean they should just go up with the hotbar, some might be the upper left corner and should go down right, etc, but there is no way to individually change these. On Forge, elements registered as overlays that aren't associated with hud elements would be possible to do so, but that is the only case.

**Comment by heythisisreal** [comment]
Wa... So interesting! I don't know how to mod but I do use Photoshop so funnily enough I actually had a similar idea and made a concept similar enough to what you're saying with the whole full screen interface.

And that last thing, you're talking about compatibility with other mods so that their interfaces could be moved? Because as cool as that sounds, I feel like that that'd be a hell of a headache... Especially dealing with the ones that are not associated with its own labeled element... 😰

![hudmod_1](https://github.com/yurisuika/Raised/assets/115737975/e572dc04-ffe0-45b5-9a31-c07aa14acde6)
![hudmod_2](https://github.com/yurisuika/Raised/assets/115737975/bd7db09f-03cb-44c5-a336-fa5f3c406a5e)

**Comment by yurisuika** [comment]
I've been slowly chipping away at this over the past month and keep changing stuff, but I've come up with a pretty good solution. I've been putting some previews up on my Discord, but here is some of what I have last set up. Been a bit slow going, I really should be making more effort into getting it done but hey distractions.

![image](https://github.com/yurisuika/Raised/assets/7410303/a2a9ed24-371d-4430-a8a7-15b20bfbdd53)

So the idea is that the user can make their own groups. They can choose which element types they want in the group. The position of the group (where its movement originates from), and then sliders for the X Y and Z... the Z index is really mainly there for fixing chat vs hotbar item conflict when Raised moves up the hotbar into the chat space. And then the option to sync the group with the first group in the list.

**Comment by yurisuika** [comment]
And then there is a little scaled preview with an animation to give it some additional context, since the sliders take the form of percentages now, so it also animates the item stack's count as your HUD x and y values.

**Comment by yurisuika** [comment]
One reason why this requires a bit more complexity is cause maybe some users may want their chat to only move up, maybe some would want it up and in, same maybe some don't want the scoreboard to move inward, but they want boss bar and potion icons to move down. Stuff that like gives the user flexibility... and thought hey maybe some want chat and scoreboard and potions to move only horizontally if say they have an ultrawide, but want boss bar the same spot and want the hotbar raised.

**Comment by yurisuika** [comment]
Work on this is virtually finished, just backporting remains and then it will see a release!

**Comment by heythisisreal** [comment]
Oh my goodness... I instantly downloaded this as soon as I realized what you did. Played with it, tweaked it... And holy moly it is so cool!!!!!! I know you already had the idea to do this but damn thank you so so much...

YOURE AWESOME AND I HOPE YOU AHVE A BEAUTIFUL DAY!!!

![2024-08-11_22 03 35](https://github.com/user-attachments/assets/c83a2232-ed23-4046-a4c9-444a17ef2a7c)
