### ISSUE TITLE
Incompatibility with IguanaTweaksReborn Regenerating Absorption (Forge 1.20.1)

### ISSUE THREAD

**Issue by Insane96** [yurisuika/Raised#87]
![image](https://github.com/yurisuika/Raised/assets/7185104/87e9c654-9bf5-4685-b7c0-4cdc28920944)
The shield icon is not rised

**Comment by yurisuika** [comment]
It looks like this mod is using RegisterGuiOverlaysEvent to register its own regenerating absorption overlay in association with its own stamina overlay. Presently, Raised only translates registered overlays on Forge if they are associated with the vanilla HUD/chat elements that it translates, or if a different method is used to register an overlay without an association (toggleable by the support option).

To support this, it wouldn't be as simple as just also translating overlays associated with anything, as the goal is to only translate certain elements. This would probably require having a list of mod overlays and their associated overlays to translate, which the user would have to configure, and at least a command to output what overlays are presently registered so the user knows what exists in the first place as well as what overlays they are associated with.

**Comment by Insane96** [comment]
Wouldn't be as simple as "increased leftHeight and rightHeight before rendering" (at least on Forge)?

**Comment by yurisuika** [comment]
Well the early versions of Raised did alter those constants, but even then there were a lot of mods that don't use them and just calculate the offset on their own. Naturally, this doesn't jive too well if their stacks are also being translated.

Sorry for the latent reply, I've been focused on trying to get another mod updated/improved for the past couple weeks.

**Comment by Insane96** [comment]
There's something I could do to fix it? The CF description says that in Fabric you can use Object Share, what about on Forge?

**Comment by yurisuika** [comment]
Well I want to look into how to make a proper API for such cases. I'm wrapping up some updates and then that is next on the list to focus on.

**Comment by yurisuika** [comment]
API is out with Raised 4.0.0.
