### ISSUE TITLE
1.21 update?

### ISSUE THREAD

**Issue by pleepish** [yurisuika/Raised#91]

**Comment by KennyDevT** [comment]
Its Not Completed tho

**Comment by yurisuika** [comment]
Well there isn't a delete button.

**Comment by yurisuika** [comment]
1.21 update is done but its not on here. But no effort issues like this just waste my time and delay the update. :)

**Comment by PukPukov** [comment]
> 1.21 update is done but its not on here. But no effort issues like this just waste my time and delay the update. :)

Why so much toxicity? It's not the issue author's fault that mojang forces you to rewrite the mod every couple of months.
