### ISSUE TITLE
Sidebar not moving Position

### ISSUE THREAD

**Issue by Partonetrain** [yurisuika/Raised#96]
Using Fabric 0.16.5, Raised 4.0.0, MC 1.20.1
![image](https://github.com/user-attachments/assets/c8e07f38-5133-49a5-bf4d-a2711d947aa9)

**Comment by yurisuika** [comment]
![image](https://github.com/user-attachments/assets/a0dfc6a7-ab9d-4355-957c-c5106ba54ba5)

Position setting is just the origin point from which the translation occurs, not the position on the screen where the element is placed. That does not change. For the most part, these do not need to change from their default values for each element type, but you can do stuff like just move everything vertically or horizontally if you adjust them. You will still need to adjust the X and Y translation values and set the sync to `none` if you wish it to be individually translated.

**Comment by Partonetrain** [comment]
Thanks for clearing that up!
