### ISSUE TITLE
[1.16.5 Crash] Game crashed when click player at option screen

### ISSUE THREAD

**Issue by GoldenTotem** [yurisuika/Raised#97]
Minecraft 1.16.5  Forge 36.2.35  Raised 4.0.0

Use ` open the option screen and click the player button, then the game will crashed.

**Comment by yurisuika** [comment]
I cannot replicate. Send logs.

It is probably a mod conflict. Someone else wrote about this a month ago and sent pic of a list of mods but never followed up. If you have any of these mods then it probably is one of them responsible.
![image](https://github.com/user-attachments/assets/f48328c1-80d0-445a-839a-206bcdfb8702)

**Comment by GoldenTotem** [comment]
> I cannot replicate. Send logs.
> 
> It is probably a mod conflict. Someone else wrote about this a month ago and sent pic of a list of mods but never followed up. If you have any of these mods then it probably is one of them responsible. ![image](https://private-user-images.githubusercontent.com/7410303/376076159-f48328c1-80d0-445a-839a-206bcdfb8702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjcyNDksIm5iZiI6MTcyOTA2Njk0OSwicGF0aCI6Ii83NDEwMzAzLzM3NjA3NjE1OS1mNDgzMjhjMS04MGQwLTQ0NWEtODM5YS0yMDZiY2RmYjg3MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDgyMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJjMjIxMGI4ZjA4ZDEzMDkzNzk1YmE3ODNkM2Y2MjE2MTU5NDNlY2E0Yjk4NzU1MTI4MDVkMTk4Mzg0NWQ1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JhZb7n8qwknrRtMuO-wPiXiE88lmc5hlM4tBaaRm1xw)

It is not a mod conflict because I had the crash with single mod. A log will be sent later.

**Comment by GoldenTotem** [comment]
> I cannot replicate. Send logs.
> 
> It is probably a mod conflict. Someone else wrote about this a month ago and sent pic of a list of mods but never followed up. If you have any of these mods then it probably is one of them responsible. ![image](https://private-user-images.githubusercontent.com/7410303/376076159-f48328c1-80d0-445a-839a-206bcdfb8702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzQzMzUsIm5iZiI6MTcyOTA3NDAzNSwicGF0aCI6Ii83NDEwMzAzLzM3NjA3NjE1OS1mNDgzMjhjMS04MGQwLTQ0NWEtODM5YS0yMDZiY2RmYjg3MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMTAyMDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2NGU5ZDE3OWVkNTc3YjRlOWM2NDYyZjkwZDE0M2VlMjZkZDVkOGEwMWNmZmI3MjhjNGE4NzYzYmIyMjk2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ILYrSS6IPLZbPdxvAuyYyMRpZhe1Z9Xd7RV7rrcc3h0)

https://mclo.gs/0Ei8a9q

**Comment by yurisuika** [comment]
Okay this seems to be the line in which it is getting your player skin. Are you by chance playing offline or anything non-standard in that regard? I'll have to test that myself.

If I can't replicate it by doing that, I can make a special build later to get additional logs iif you'd be willing to test it. If it isn't that your skin is null then it might be your game profile which is. Either way, the fact is something is not present that should be.

**Comment by GoldenTotem** [comment]
> Okay this seems to be the line in which it is getting your player skin. Are you by chance playing offline or anything non-standard in that regard? I'll have to test that myself.
> 
> If I can't replicate it by doing that, I can make a special build later to get additional logs iif you'd be willing to test it. If it isn't that your skin is null then it might be your game profile which is. Either way, the fact is something is not present that should be.

It is true that i am playing offline, because i used to playing offline when testing my game. :)

**Comment by yurisuika** [comment]
Okay yes, I see it produces the null. I think to fix this I'll either conditionally have it just use the steve and alex skins as fallbacks or maybe even just entirely replace pulling the user and Notch skin.
